create table if not exists public.bookings (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    customer_name text not null,
    customer_phone text not null,
    customer_whatsapp text,
    service text,
    booking_date text,
    booking_time text,
    notes text,
    price numeric
);

alter table public.bookings enable row level security;

create policy "Allow anonymous read access on bookings"
    on public.bookings for select
    to anon
    using (true);

create policy "Allow anonymous insert access on bookings"
    on public.bookings for insert
    to anon
    with check (true);
    
create policy "Allow anonymous delete access on bookings"
    on public.bookings for delete
    to anon
    using (true);
    
create policy "Allow anonymous update access on bookings"
    on public.bookings for update
    to anon
    using (true);
